### ISSUE TITLE
The example is not even working

### ISSUE THREAD

**Issue by dheerajbred** [LinusU/flutter_marionette#1]
Getting this error

```
E/flutter ( 3579): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method init on channel flutter_marionette)
E/flutter ( 3579): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
E/flutter ( 3579): <asynchronous suspension>
E/flutter ( 3579): #1      new Marionette (package:flutter_marionette/marionette.dart:17:38)
E/flutter ( 3579): #2      _MyAppState.scrape (package:AnimePrime/main.dart:31:18)
E/flutter ( 3579): <asynchronous suspension>
E/flutter ( 3579): #3      _MyAppState.build.<anonymous closure> (package:AnimePrime/main.dart:57:38)
E/flutter ( 3579): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:511:14)
E/flutter ( 3579): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:566:30)
E/flutter ( 3579): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
E/flutter ( 3579): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:240:9)
E/flutter ( 3579): #8      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:177:9)
E/flutter ( 3579): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:436:9)
E/flutter ( 3579): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter ( 3579): #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter ( 3579): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:221:19)
E/flutter ( 3579): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:199:22)
E/flutter ( 3579): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 3579): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 3579): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 3579): #17     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter ( 3579): #18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 3579): #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter ( 3579): #20     _invoke1 (dart:ui/hooks.dart:233:10)
E/flutter ( 3579): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)
E/flutter ( 3579):
```

**Comment by LinusU** [comment]
Sorry for the late reply, been out traveling...

I haven't yet implemented the Android part of this library, but I hope to get to it within the coming months...

**Comment by dheerajbred** [comment]
Oh okay
:)

**Comment by silverfox983** [comment]
I'de really like to see this working for android.

**Comment by cincrain** [comment]
Really looking forward to it for android, too.

**Comment by cincrain** [comment]
line 61  final page = Marionette();
line 62  await page.goto(GWANGJIN_LIB_SEARCH_PAGE);

Getting this error -->>

E/flutter (14503): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method init on channel flutter_marionette)
E/flutter (14503): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter (14503): <asynchronous suspension>
E/flutter (14503): #1      new Marionette (package:flutter_marionette/marionette.dart:17:38)
E/flutter (14503): #2      _onInit (package:wish_book/src/views/wishbook_scrap_page/effect.dart:61:18)
E/flutter (14503): #3      combineEffects.<anonymous closure> (package:fish_redux/src/redux_component/helper.dart:74:32)
E/flutter (14503): #4      EnhancerDefault._inverterEffect.<anonymous closure> (package:fish_redux/src/redux_component/enhancer.dart:117:56)
E/flutter (14503): #5      _pageAnalyticsMiddleware.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:wish_book/app.dart:139:24)
E/flutter (14503): #6      createEffectDispatch.<anonymous closure> (package:fish_redux/src/redux_component/helper.dart:89:39)
E/flutter (14503): #7      createDispatch.<anonymous closure> (package:fish_redux/src/redux_component/helper.dart:109:39)
E/flutter (14503): #8      LogicContext.onLifecycle (package:fish_redux/src/redux_component/context.dart:92:5)
E/flutter (14503): #9      ComponentContext.onLifecycle (package:fish_redux/src/redux_component/context.dart:203:11)
E/flutter (14503): #10     ComponentState.initState (package:fish_redux/src/redux_component/component.dart:224:10)
E/flutter (14503): #11     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
E/flutter (14503): #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (14503): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (14503): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (14503): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (14503): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (14503): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (14503): #18     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
E/flutter (14503): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (14503): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (14503): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (14503): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (14503): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (14503): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (14503): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (14503): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (14503): #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (14503): #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (14503): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (14503): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (14503): #31     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (14503): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (14503): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (14503): #34     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (14503): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (14503): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (14503): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (14503): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (14503): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (14503): #40     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
E/flutter (14503): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (14503): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (14503): #43     Element.updateChild (package
